### ISSUE TITLE
Server starting error

### ISSUE THREAD

**Issue by zoewood** [InfoScribe/infoscribe-www#1]
'npm start' currently causes an error

The error looks like this: 

/Users/zoewood/InfoScribe/infoscribe-www/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:83
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clie
                                 ^
TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/Users/zoewood/InfoScribe/infoscribe-www/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:83:34)
    at new Strategy (/Users/zoewood/InfoScribe/infoscribe-www/node_modules/passport-facebook/lib/strategy.js:55:18)
    at Object.<anonymous> (/Users/zoewood/InfoScribe/infoscribe-www/routes/passport.js:53:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/zoewood/InfoScribe/infoscribe-www/server.js:141:13)

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.8
npm ERR! code ELIFECYCLE
npm ERR! infoscribe-www@0.0.1 start: `node server.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the infoscribe-www@0.0.1 start script 'node server.js'.
npm ERR! This is most likely a problem with the infoscribe-www package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls infoscribe-www
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zoewood/InfoScribe/infoscribe-www/npm-debug.log

**Comment by iaincollins** [comment]
This error is raised as oAuth details are not specified in `config/secrets.js`:

```
TypeError: OAuth2Strategy requires a clientID option
```

These details are not committed to the repo as they should never be public. They can be specified there locally, but in production you can see they are read from environment variables.

You can edit `config/secrets.js` to put in dummy values but if you actually want to test the login system you would need to register with the oAuth providers in `config/secrets.js` and specify oAuth endpoints that point back to localhost + routes for callbacks that are defined in the server.js.

e.g. Use `http://localhost:3000/auth/facebook/callback` as the callback URL for Facebook.
